import { Property } from "@/lib/types";

export const properties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    description: "A beautiful modern apartment in the heart of downtown with stunning city views. Features include high ceilings, floor-to-ceiling windows, and premium finishes throughout.",
    price: 1200,
    location: "Downtown, Lomé",
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Air Conditioning", "Gym", "Parking", "Security"],
    availableFrom: "2025-05-01",
  },
  {
    id: "2",
    title: "Beachfront Villa",
    description: "Luxury beachfront villa with private access to the beach. Enjoy panoramic ocean views from multiple terraces and a beautiful garden with a swimming pool.",
    price: 2500,
    location: "Avepozo Beach, Lomé",
    bedrooms: 4,
    bathrooms: 3,
    area: 240,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&auto=format&fit=crop",
    amenities: ["Swimming Pool", "Beach Access", "Garden", "Air Conditioning", "Security", "Parking"],
    availableFrom: "2025-04-15",
  },
  {
    id: "3",
    title: "Cozy Studio Apartment",
    description: "Compact and functional studio apartment ideal for students or professionals. Well-designed space with modern furnishings and excellent location near universities.",
    price: 450,
    location: "University Area, Lomé",
    bedrooms: 0,
    bathrooms: 1,
    area: 35,
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "Laundry Facilities"],
    availableFrom: "2025-04-01",
  },
  {
    id: "4",
    title: "Family Home with Garden",
    description: "Spacious family home in a quiet residential area with a beautiful garden and play area for children. Close to schools, parks, and shopping centers.",
    price: 1800,
    location: "Adidogomé, Lomé",
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop",
    amenities: ["Garden", "Parking", "Security", "Air Conditioning", "Pets Allowed"],
    availableFrom: "2025-06-01",
  },
  {
    id: "5",
    title: "Luxury Penthouse",
    description: "Exclusive penthouse apartment with panoramic city views, featuring premium finishes, a private terrace, and state-of-the-art amenities.",
    price: 3000,
    location: "GTA, Lomé",
    bedrooms: 3,
    bathrooms: 3,
    area: 180,
    image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&auto=format&fit=crop",
    amenities: ["Terrace", "Gym", "Parking", "Security", "Air Conditioning", "Swimming Pool"],
    availableFrom: "2025-05-15",
  },
  {
    id: "6",
    title: "Modern 2-Bedroom Apartment",
    description: "Well-designed 2-bedroom apartment in a new building with modern amenities and easy access to public transportation.",
    price: 950,
    location: "Tokoin, Lomé",
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Air Conditioning", "Parking", "Security"],
    availableFrom: "2025-04-10",
  },
];